galvez/urls.py
from django.contrib import admin
from django.urls import include, path
from static import views as static_views
from buscador import views as buscador_views

urlpatterns = [
    path('', static_views.inicio, name='inicio'),
    path('acerca/', static_views.acerca, name='acerca'),
    path('buscador/', buscador_views.buscador, name='buscador'),
    path('personas/', include('personas.urls')),
    path('lugares/', include('lugares.urls')),
    path('admin/', admin.site.urls),
]

personas/urls.py
from django.urls import path

from . import views

app_name = 'personas'
urlpatterns = [
    path('', views.index, name='index'),
    path('lista_personas/', views.lista_personas, name='lista_personas'),
    path('<int:persona_id>/', views.detalle_persona, name='detalle_persona'),
    path('buscador_persona/', views.buscador_persona, name='buscador_persona'),
]

actividades/models.py
# actividades/model.py

from django.db import models
from personas.models import Persona
from lugares.models import Localidad, Jurisdiccion, Provincia

class TipoCargo(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class TituloCargo(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    tipo_cargo = models.ForeignKey(TipoCargo, on_delete=models.CASCADE, null=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class Cargo(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, null=True, blank=True)
    titulo_cargo = models.ForeignKey(TituloCargo, on_delete=models.CASCADE, null=True, blank=True)
    localidad = models.ForeignKey(Localidad, on_delete=models.CASCADE, null=True, blank=True)
    jurisdiccion = models.ForeignKey(Jurisdiccion, on_delete=models.CASCADE, null=True, blank=True)
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE, null=True, blank=True)
    fecha_inicio = models.IntegerField(null=True, blank=True)
    fecha_final = models.IntegerField(null=True, blank=True)
    notas = models.TextField(blank=True)
    class Meta:
        ordering = ["fecha_inicio", "fecha_final"]
    def __str__(self):
        return "%s | %s | %s | %s | %s | %d | %d" % (self.persona, self.titulo_cargo, self.localidad, self.jurisdiccion, self.provincia, self.fecha_inicio, self.fecha_final)

galvez/personas/models.py
# personas/models.py

from django.db import models
from lugares.models import Localidad

class Persona(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    ordenar_por_nombre = models.CharField(max_length=100, blank=True)
    genero = models.CharField(max_length=765, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    lugar_nacimiento = models.ForeignKey(Localidad, related_name='nacimiento', on_delete=models.CASCADE, null=True, blank=True)
    fecha_defuncion = models.DateField(null=True, blank=True)
    lugar_defuncion = models.ForeignKey(Localidad, on_delete=models.CASCADE, null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class TipoResidencia(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    temporal = models.NullBooleanField(null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class Residencia(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, null=True)
    localidad = models.ForeignKey(Localidad, on_delete=models.CASCADE, null=True)
    tipo_residencia = models.ForeignKey(TipoResidencia, on_delete=models.CASCADE, null=True, blank=True)
    fecha_inicio = models.IntegerField(null=True, blank=True)
    fecha_final = models.IntegerField(null=True, blank=True)
    lugar_nacimiento = models.NullBooleanField(null=True, blank=True)
    lugar_defuncion = models.NullBooleanField(null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return '%s, %s' % (self.persona, self.tipo_residencia)

class TipoOcupacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class TituloOcupacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    tipo_ocupacion = models.ForeignKey(TipoOcupacion, on_delete=models.CASCADE, null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class Ocupacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, null=True)
    titulo_ocupacion = models.ForeignKey(TituloOcupacion, on_delete=models.CASCADE, null=True)
    fecha_inicio = models.IntegerField(null=True, blank=True)
    fecha_final = models.IntegerField(null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return '%s, %s' % (self.persona, self.titulo_ocupacion)

class TipoRelacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class Relacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona_id_1 = models.ForeignKey(Persona, related_name='persona_1', on_delete=models.CASCADE, null=True)
    persona_id_2 = models.ForeignKey(Persona, related_name='persona_2', on_delete=models.CASCADE, null=True)
    tipo_relacion = models.ForeignKey(TipoRelacion, on_delete=models.CASCADE, null=True)
    fecha_inicio = models.IntegerField(null=True, blank=True)
    fecha_final = models.IntegerField(null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return '%s and %s' % (self.persona_id_1, self.persona_id_2)

class Actividad(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, null=True)
    fecha = models.IntegerField(null=True, )
    actividad = models.TextField(blank=True)
    fuente = models.CharField(max_length=765, blank=True)
    def __str__(self):
        return self.actividad

personas/models.py
# personas/models.py

from django.db import models
from lugares.models import Localidad

class Persona(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    ordenar_por_nombre = models.CharField(max_length=100, blank=True)
    genero = models.CharField(max_length=765, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    lugar_nacimiento = models.ForeignKey(Localidad, related_name='nacimiento', on_delete=models.CASCADE, null=True, blank=True)
    fecha_defuncion = models.DateField(null=True, blank=True)
    lugar_defuncion = models.ForeignKey(Localidad, on_delete=models.CASCADE, null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class TipoResidencia(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    temporal = models.BooleanField(null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class Residencia(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, null=True)
    localidad = models.ForeignKey(Localidad, on_delete=models.CASCADE, null=True)
    tipo_residencia = models.ForeignKey(TipoResidencia, on_delete=models.CASCADE, null=True, blank=True)
    fecha_inicio = models.IntegerField(null=True, blank=True)
    fecha_final = models.IntegerField(null=True, blank=True)
    lugar_nacimiento = models.BooleanField(null=True, blank=True)
    lugar_defuncion = models.BooleanField(null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return '%s, %s' % (self.persona, self.tipo_residencia)

class TipoOcupacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class TituloOcupacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    tipo_ocupacion = models.ForeignKey(TipoOcupacion, on_delete=models.CASCADE, null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class Ocupacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, null=True)
    titulo_ocupacion = models.ForeignKey(TituloOcupacion, on_delete=models.CASCADE, null=True)
    fecha_inicio = models.IntegerField(null=True, blank=True)
    fecha_final = models.IntegerField(null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return '%s, %s' % (self.persona, self.titulo_ocupacion)

class TipoRelacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    nombre = models.CharField(max_length=765)
    notas = models.TextField(blank=True)
    def __str__(self):
        return self.nombre

class Relacion(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona_id_1 = models.ForeignKey(Persona, related_name='persona_1', on_delete=models.CASCADE, null=True)
    persona_id_2 = models.ForeignKey(Persona, related_name='persona_2', on_delete=models.CASCADE, null=True)
    tipo_relacion = models.ForeignKey(TipoRelacion, on_delete=models.CASCADE, null=True)
    fecha_inicio = models.IntegerField(null=True, blank=True)
    fecha_final = models.IntegerField(null=True, blank=True)
    notas = models.TextField(blank=True)
    def __str__(self):
        return '%s and %s' % (self.persona_id_1, self.persona_id_2)

class Actividad(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, null=True)
    fecha = models.IntegerField(null=True, )
    actividad = models.TextField(blank=True)
    fuente = models.CharField(max_length=765, blank=True)
    def __str__(self):
        return self.actividad

personas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Persona

def index(request):
    return HttpResponse("Ya llegaste hasta el índice de personas del proyecto Gálvez. ¿Y ahora?")

def lista_personas(request):
    return render(request, 'personas/lista_personas.html', {'personas': Persona.objects.all().order_by('ordenar_por_nombre')})

def detalle_persona(request, persona_id):
    persona = get_object_or_404(Persona, pk=persona_id)
    return render(request, 'personas/detalle_persona.html', {'persona': persona})

import re

from django.db.models import Q

def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:
        
        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']
        
        '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]

def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.
        
        '''
    query = None # Query to search for every search term
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query


def buscador_persona(request):
    if 'q' in request.GET:
        query_string = request.GET['q']
        entry_query = get_query(query_string, ['nombre', 'notas'])
        personas = Persona.objects.filter(entry_query).distinct().order_by("ordenar_por_nombre")
    return  render(request, 'personas/buscador_persona.html', {'query_string': query_string, 'personas': personas})

personas/templates/personas/buscador_persona.html
{% extends "galvez_base.html"%}


{% block title %} Búsqueda personas | {{block.super}}{% endblock %}

{% block main%}
	<div id="main">
		<div id="content">
		{% block content %}
			<h3 class="browse_title">Búsqueda de personas</h3>
				<form action="" method="get">
					<p>
						<span class="search_param">Búsqueda original: </span>
						<input type="text" name="q" value="{{ query_string }}">
						<input type="submit" value="Buscar">
						<a href="/buscador/">volver</a>
					</p>
				</form>
			<h3><b>Results ({{ personas|length }} total)</b></h3>
				<ul>
					{% for persona in personas %}
					<li><a href="/personas/{{persona.id}}">{{ persona }}</a></li>
					{% endfor %}
				</ul>
		{% endblock %}
{% endblock %}

personas/templates/personas/detalle_persona.html
{% extends "galvez_base.html" %}

{% block title %}{{persona.nombre}} | {{block.super}}{% endblock %}

{% block scripts %}
<!-- Para los scripts de jquery y otras cosas -->
{% endblock %}

{% block main %}
<!-- No entiendo el porqué pero hay que dejar un espacio aquí -->
<div id=cuerpo">
    <div id="ficha">
        <h2>Ficha de persona</h2>
        <h4>Datos generales:</h4>
        <p><b>Nombre:</b> {{ persona.nombre|default_if_none:"" }} <br>
        <b>Género:</b> {{ persona.genero|default_if_none:"" }} <br>
        <b>Fecha de nacimiento:</b> {{ persona.fecha_nacimiento|default_if_none:"" }} <br>
        <b>Lugar de nacimiento:</b> <a href="/lugares/{{ persona.lugar_nacimiento.id }}/">{{ persona.lugar_nacimiento|default_if_none:"" }}</a> <br>
        <b>Fecha de defunción:</b> {{ persona.fecha_defuncion|default_if_none:"" }} <br>
        <b>Lugar de defunción:</b> <a href="/lugares/{{ persona.lugar_defuncion.id }}/">{{ persona.lugar_defuncion|default_if_none:"" }}</a> <br>
        <b>Notas:</b> {{ persona.notas|default_if_none:"" }} </p>
        <p><a href="/personas/lista_personas">(volver a la lista de personas)</a></p>
    </div>
    <div id="ocupaciones">
        <h4 id=ocupaciones>Títulos académicos, militares y nobiliarios</h4>
        <table>
            <th>Título</th>
            <th>Fechas</th>
            <th>Notas</th>
            {% for ocupacion in persona.ocupacion_set.all %}
                <tr>
                    <td>{{ocupacion.titulo_ocupacion}}</td>
                    <td>{{ocupacion.fecha_inicio|default_if_none:""}} - {{ocupacion.fecha_final|default_if_none:""}}</td>
                    <td>{{ocupacion.notas}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div id="cargos"></div>
        <h4>Cargos</h4>
        <table class="cuatro_columnas">
            <th class="nombre_campo">Cargo</th>
            <th class="nombre_campo">local</th>
            <th class="nombre_campo">en jurisdicción</th>
            <th class="nombre_campo">provincial</th>
            <th class="nombre_campo">Fechas</th>
            <th class="nombre_campo">Notas</th>
            {% for cargo in persona.cargo_set.all %}
                <tr>
                    <td>{{cargo.titulo_cargo}}</td>
                    <td><a href="/lugares/{{ cargo.localidad.id }}/">{{cargo.localidad|default_if_none:""}}</a></td>
                    <td><a href="/lugares/detalle_jurisdiccion/{{ cargo.jurisdiccion.id }}/">{{cargo.jurisdiccion|default_if_none:""}}</a></td>
                    <td><a href="/lugares/detalle_provincia/{{ cargo.provincia.id }}/">{{cargo.provincia|default_if_none:""}}</a></td>
                    <td>{{cargo.fecha_inicio}} - {{cargo.fecha_final}}</td>
                    <td class="notas">{{cargo.notas}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div>
        <h4>Actividades</h4>
        <table>
            <th>Año</th>
            <th>actividad</th>
            <th>fuente</th>
            {% for actividad in persona.actividad_set.all %}
                <tr>
                    <td>{{actividad.fecha}}</td>
                    <td>{{actividad.actividad}}</td>
                    <td>{{actividad.fuente}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

personas/templates/personas/lista_personas.html
{% extends "galvez_base.html" %}

{% block title %}Personas | {{block.super}}{% endblock %}

{% block main %}

<h2>Personas (total en la BD: {{ personas|length }} )</h2>
<ul>
    {% for persona in personas %}
        <li><a href="/personas/{{ persona.id }}/"> {{ persona }}</a></li>
    {% endfor %}
</ul>

{% endblock %}